### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by sallu1001** [Glamdring/epassport-reader#1]
Hello,

Thanks for sharing the open source code for reading passport info but I'm facing an issue while using the app. It's crashing as soon as I start using it. I'm getting some logs which I'm sharing below. Kindly help me to sort this out. Any help would be appreciable.
Thanks

[ FATAL EXCEPTION: main
                                                                      Process: bg.bozho.emrtdreader, PID: 28116
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{bg.bozho.emrtdreader/bg.bozho.emrtdreader.MainActivity}: java.lang.IllegalArgumentException
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                       Caused by: java.lang.IllegalArgumentException
                                                                          at net.sf.scuba.smartcards.CardService.getInstance(Unknown Source)
                                                                          at bg.bozho.emrtdreader.MainActivity.onCreate(MainActivity.java:72)
                                                                          at android.app.Activity.performCreate(Activity.java:6245)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) ](url)

**Comment by Glamdring** [comment]
Sorry for the delay - does your phone support NFC? Or this is run via an emulator (which potentially doesn't have NFC)

**Comment by sallu1001** [comment]
Yes my phone supports NFC and I'm not running it on emulator.

**Comment by Glamdring** [comment]
Check the permissions. Basically the error means no NFC is available

**Comment by sallu1001** [comment]
Ok I will do that and revert asap. Thanks for the reply. :)
